<template lang="html">
  <div class="container">
    <div id="" class="card left grey lighten-2 scale-up-center" style="height: 88%; width: 125%; margin: 10% 0 0 -10%; padding: 0 0 0 0; position:static;">
      <div class="container">
        <br>
        <h4><b>Edit question</b></h4>
        <div class="row">
          <div class="input-field col s12">
            <input id="title" type="text" class="validate" v-model='newTitle'>
            <label for="title">Title</label>
          </div>
          <div id="sample" class="col s12">
            <h6>
              <b>Enter your question here:</b>
            </h6>
            <br>
            <div>
              <Vueditor ref="editor" style="position:static;"></Vueditor>
              <br/>
            </div>
          </div>
          </div>
        </div>
        <div class="card-action">
          <div class="row">
            <div class="container">
              <div class="col s6">
                <a class="btn btn-block waves-effect waves-btn blue-grey darken-4" style="margin: 3% 0 0 0; width:100%;" @click='cancel'>Cancel</a>
              </div>
              <div class="col s6">
                <a class="btn btn-block waves-effect waves-btn blue-grey darken-4" style="margin: 3% 0 0 0; width:100%;" @click=''>Post</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</template>

<script>
import axios from 'axios'
import Vueditor from 'vueditor'

export default {
  data () {
    return {
      dataEdit: null,
      newTitle: ''
    }
  },
  created () {
    this.dataEdit = this.$store.state.detail
    this.newTitle = this.$store.state.detail.title
    this.$refs.editor.setContent(this.$store.state.detail.description)
  },
  mounted () {
    this.$refs.editor.setContent(this.dataEdit.description)
  },
  component : {
    Vueditor
  },
  methods : {
    cancel () {
      this.$router.push('/')
    },
    post () {
      console.log();
    }
  }
}
</script>

<style scoped>
.scale-up-center {
	-webkit-animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
	        animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2018-7-3 0:53:39
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
            transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}
@keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
            transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}

</style>
