<template>
  <div class="body-background">
    <div class="row" style="margin: 5% 0 0 4.5%;">
      <div class="col s12 m12 slide-fwd-bottom" v-for='question in questions'>
        <div class="card grey darken-3">
          <div class="card-content white-text">
            <div class="row">
              <div class="col">
                <span class="card-title">{{ question.title }}</span>
                <pre style="color:grey;">From: {{ question.UserId.username }}</pre>
              </div>
              <div class="col right" style="margin: -1% 0 0 0;">
                <pre style="color:grey;">{{ question.time }}</pre>
              </div>
            </div>
            <div class="" style="margin: -1% 3% 0 4%;">
              <article class="">
                <p >{{ question.description.split('<\/p>')[0].split(';">')[1] }} . . . </p>
              </article>
            </div>
            <br>
            <div class="row" style="margin: 0 0 0 -1%;">
              <div class="col">
                <pre style="color:grey;">Comments: {{ question.answer.length }}</pre>
              </div>
              <div class="col">
                <pre style="color:grey;">Upvotes: {{ question.votes.length }}</pre>
              </div>
              <div class="col">
                <pre style="color:grey;">Downvotes: {{ question.downvotes.length }}</pre>
              </div>
            </div>
          </div>
          <div class="card-action" style="text-align:right;">
            <a class="btn card waves-effect waves-dark red darken-4" style="position:static; margin: 0 0 0 0;" @click='openDetail(question)'>Open detail</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import Vueditor from 'vueditor'

export default {
  created () {
    this.getAllQuestion()
    this.$store.dispatch('UserData', localStorage.getItem('authorization').split('*#$_.')[1])
  },
  components : (
    Vueditor
  ),
  computed: {
    questions () {
      return this.$store.state.questions
    }
  },
  methods: {
    getAllQuestion () {
      this.$store.dispatch('getAllQuestion')
    },
    openDetail (question) {
      this.$store.dispatch('getAnswer', question._id)
      this.$store.dispatch('openDetail', question)
      this.$router.push('detail')
    }
  }
}
</script>

<style lang="css">
  .body-background{
    text-align: left;
    height: 100%;
    width: 100%;
  }
  article {
    display: block;
  }
  .slide-fwd-bottom {
  	-webkit-animation: slide-fwd-bottom 0.45s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
  	        animation: slide-fwd-bottom 0.45s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
  }
  /* ----------------------------------------------
   * Generated by Animista on 2018-7-2 19:13:53
   * w: http://animista.net, t: @cssanimista
   * ---------------------------------------------- */

  /**
   * ----------------------------------------
   * animation slide-fwd-bottom
   * ----------------------------------------
   */
  @-webkit-keyframes slide-fwd-bottom {
    0% {
      -webkit-transform: translateZ(0) translateY(-110%);
              transform: translateZ(0) translateY(-110%);
    }
    100% {
      -webkit-transform: translateZ(160px) translateY(-10%);
              transform: translateZ(160px) translateY(0px);
    }
  }
  @keyframes slide-fwd-bottom {
    0% {
      -webkit-transform: translateZ(0) translateY(-110%);
              transform: translateZ(0) translateY(-110%);
    }
    100% {
      -webkit-transform: translateZ(160px) translateY(-10%);
              transform: translateZ(160px) translateY(0px);
    }
  }
</style>
